### ISSUE TITLE
Mail Notifications

### ISSUE THREAD

**Issue by BelGoat** [JasonRivers/Docker-Nagios#28]
I've might missed something:
How do you configure the mail sending from the Docker?
As of my tests I couldn't find a way to send mail from the nagios.
How did you fixed the issue?

**Comment by BelGoat** [comment]
After much tests and checks I've found something interesting.
My configuration in the nagios didn't have the "From" this this would not work.
Secondly the mail won't get out due to the postfix configuration (at least that is what I found)

I did change the /etc/postfix/main.cf configuration with my own relay and allowed relay IP's
If you think this is relevant - Please tell me and I will provide a new docker file with params that will help with this configuration when you create the docker instance (I also will add another user for nagios to solve the issue that this only work with nagios user).

**Comment by aryak93** [comment]
I also ran into the same issue. If possible please share the Dockerfile.

**Comment by JasonRivers** [comment]
I believe this is now solved from commit 3977816 (latest build on docker hub) Please re-open if that's not the case.

**Comment by timokli** [comment]
Hi, unfortunately its still not working with a clean new installation. As BelGoat already mentioned its because of a missing "relayhost =" in the main.cf of postfix. If I add manually the IP of my Docker host where a Mailserver is running its working as expected.

Is it possible to put this config to an ENV variable? So everybody could configure the relay host by setting the IP to ENV_RELAYHOST for example.

**Comment by JasonRivers** [comment]
With the latest build (once it's build) you should be able to set -e MAIL_RELAY_HOST to fix this, I'm not seeing this myself, the MX delivery is working as expected. Please let me know if this doesn't solve your issue.

**Comment by timokli** [comment]
Great, its working! Thanks a lot! 👍

**Comment by clarencemills** [comment]
Hello Jason,

I recently started using your docker image, works great but I'm unable to send mail. Is this what happens if you don't set the Mail_RELAY_HOST?
